import { RawBuffer } from './RawBuffer';

export enum RecvID {
    ID_NULL,
    ID_EXCEPTION,
    ID_OPEN,
    ID_QUIT,
    ID_EVENT,
    ID_EVENT_OBJECT_ADDREMOVE,
    ID_EVENT_FILENAME,
    ID_EVENT_FRAME,
    ID_SIMOBJECT_DATA,
    ID_SIMOBJECT_DATA_BYTYPE,
    ID_WEATHER_OBSERVATION,
    ID_CLOUD_STATE,
    ID_ASSIGNED_OBJECT_ID,
    ID_RESERVED_KEY,
    ID_CUSTOM_ACTION,
    ID_SYSTEM_STATE,
    ID_CLIENT_DATA,
    ID_EVENT_WEATHER_MODE,
    ID_AIRPORT_LIST,
    ID_VOR_LIST,
    ID_NDB_LIST,
    ID_WAYPOINT_LIST,
    ID_EVENT_MULTIPLAYER_SERVER_STARTED,
    ID_EVENT_MULTIPLAYER_CLIENT_STARTED,
    ID_EVENT_MULTIPLAYER_SESSION_ENDED,
    ID_EVENT_RACE_END,
    ID_EVENT_RACE_LAP,
    // KittyHawk:
    ID_EVENT_EX1,
    ID_FACILITY_DATA,
    ID_FACILITY_DATA_END,
    ID_FACILITY_MINIMAL_LIST,
    ID_JETWAY_DATA,
    ID_CONTROLLERS_LIST,
    ID_ACTION_CALLBACK,
    ID_ENUMERATE_INPUT_EVENTS,
    ID_GET_INPUT_EVENT,
    ID_SUBSCRIBE_INPUT_EVENT,
    ID_ENUMERATE_INPUT_EVENT_PARAMS,
    ID_ENUMERATE_SIMOBJECT_AND_LIVERY_LIST,
    ID_FLOW_EVENT,
}

export interface SimConnectMessage {
    protocolVersion: number;
    packetTypeId: RecvID;
    data: RawBuffer;
}
